#include "emoji_list.h"

const EmojiMap kEmojis[] =
{
                        // Pepe

    { L":widepeepoHappy:",      L"$fff时间自定$z$s" },
    { L":Prayge:",              L"$fff源$z$s" },
    { L":MonkaW:",              L"$fff专$z$s" },
    { L":Dentge:",              L"$fff内部$z$s" },
    { L":Pepega:",              L"$fff奖$z$s" },
    { L":EZY:",                 L"$fff章$z$s" },
    { L":YEP:",                 L"$fff音$z$s" },
    { L":FeelsStrongMan:",      L"$fff效$z$s" },
    { L":PepoG:",               L"$fff位$z$s" },
    { L":FeelsGoodMan:",        L"$fff置$z$s" },
    { L":PepeLaugh:",           L"$fff此$z$s" },
    { L":COPIUM:",              L"$fff挑$z$s" },
    { L":WICKED:",              L"$fff锁$z$s" },
    { L":PauseChamp:",          L"$fff尾$z$s" },
    { L":Sadge:",               L"$fff激$z$s" },
    { L":Business:",            L"$fff互$z$s" },
    { L":HmmNotes:",            L"$fff点$z$s" },
    { L":HYPERS:",              L"$fff我$z$s" },
    { L":peepoBlush:",          L"$fff防$z$s" },
    { L":peepoClown:",          L"$fff墙$z$s" },
    { L":widepeepoHug:",        L"$fff报警按下$z$s" },
    { L":Bedge:",               L"$fff成$z$s" },
    { L":MonkaSteer:",          L"$fff道$z$s" },
    { L":Chatting:",            L"$fff狂$z$s" },
    { L":pepeCringe:",          L"$fff记$z$s" },
    { L":peepoIgnore:",         L"$fff查$z$s" },
    { L":good game:",           L"$fff比$z$s" },
    { L":peepoMonster:",        L"$fff无$z$s" },
    { L":peepopCorn:",          L"$fff访$z$s" },
    { L":PETTHEPEEPO:",         L"$fff服$z$s" },
    { L":gma:",                 L"$fff务$z$s" },
    { L":Hugg:",                L"$fff器$z$s" },
    { L":Staree:",              L"$fff没$z$s" },
    { L":monkaEyes:",           L"$fff有错误初$z$s" },
    { L":Evilge:",              L"$fff化$z$s" },
    { L":Demonge:",             L"$fff应$z$s" },
    { L":FeelsBadMan:",         L"$fff要$z$s" },

                        // Twitch

    { L":xdd:",                 L"$fff最$z$s" },
    { L":OMEGALUL:",            L"$fff佳$z$s" },
    { L":Pog:",                 L"$fff义$z$s" },
    { L":Clueless:",            L"$fff家$z$s" },
    { L":BalloonCAT:",          L"$fff资$z$s" },
    { L":5Head:",               L"$fff表$z$s" },
    { L":MONKA:",               L"$fff题列$z$s" },
    { L":forsenCD:",            L"$fff标$z$s" },
    { L":WeirdChamp:",          L"$fff文$z$s" },
    { L":KEKW:",                L"$fff战$z$s" },
    { L":SadCatW:",             L"$fff住$z$s" },
    { L":o7:",                  L"$fff迹$z$s" },
    { L":Kappa:",               L"$fff目$z$s" },
    { L":Podcaster:",           L"$fff活$z$s" },
    { L":catRose:",             L"$fff联$z$s" },
    { L":t3moment:",            L"$fff戏$z$s" },
    { L":LULE:",                L"$fff数$z$s" },
    { L":sunglassescat:",       L"$fff据$z$s" },
    { L":Waiting:",             L"$fff交$z$s" },
    { L":Life:",                L"$fff换$z$s" },
    { L":Clap:",                L"$fff系$z$s" },
    { L":e:",                   L"$fff统$z$s" },
    { L":MINIONLMAO:",          L"$fff网游$z$s" },
    { L":catHUH:",              L"$fff对$z$s" },
    { L":WAJAJA:",              L"$fff建$z$s" },
    { L":thonk:",               L"$fff测$z$s" },
    { L":pengun:",              L"$fff络$z$s" },
    { L":angry:",               L"$fff连$z$s" },
    { L":disbelief:",           L"$fff火$z$s" },
    { L":pikawow:",             L"$fff车$z$s" },
    { L":gay:",                 L"$fff在$z$s" },
    { L":fatass:",              L"$fff上次计重$z$s" },
    { L":goggers:",             L"$fff竞$z$s" },
    { L":sniffa:",              L"$fff飙$z$s" },
    { L":D::",                  L"$fff影$z$s" },
    { L":cowJAM:",              L"$fff录$z$s" },
    { L":yippie:",              L"$fff到$z$s" },
    { L":opice:",               L"$fff理$z$s" },
    { L":war:",                 L"$fff设$z$s" },
    { L":HUH:",                 L"$fff需$z$s" },
    { L":bonk:",                L"$fff主$z$s" },
    { L":ta:",                  L"$fff钟$z$s" },
    { L":baller:",              L"$fff密$z$s" },

                        //Custom

    { L":skull:",               L"$fff问$z$s" },
    { L":Smirk Cat:",           L"$fff普通$z$s" },
    { L":Joy:",                 L"$fff轴$z$s" },
    { L":Sob:",                 L"$fff本$z$s" },
    { L":heart:",               L"$fff被$z$s" },
    { L":Love smile:",          L"$fff了$z$s" },
    { L":saluting face:",       L"$fff为$z$s" },
    { L":popcorn:",             L"$fff和$z$s" },
    { L":fire:",                L"$fff们$z$s" },
    { L":kms:",                 L"$fff议$z$s" },
    { L":turtle:",              L"$fff您$z$s" },
    { L":pray:",                L"$fff试$z$s" },
    { L":noooo:",               L"$fff接$z$s" },
    { L":brain:",               L"$fff可$z$s" },
    { L":nerd:",                L"$fff能$z$s" },
    { L":logodiscord:",         L"$fff会$z$s" },
    { L":logotwitch:",          L"$fff导$z$s" },
    { L":logoinstagram:",       L"$fff致$z$s" },
    { L":logosnapchat:",        L"$fff的$z$s" },
    { L":wave:",                L"$fff回$z$s" },
    { L":raised eyebrow:",      L"$fff键$z$s" },
    { L":unorev:",              L"$fff新$z$s" },
    { L":kys:",                 L"$fff开$z$s" },
    { L":getout:",              L"$fff始$z$s" },
    { L":bryson:",              L"$fff赛$z$s" },
    { L":cap:",                 L"$fff完$z$s" },
    { L":sexo:",                L"$fff子$z$s" },
    { L":flushed:",             L"$fff看$z$s" },
    { L":SCTrophie:",           L"$fff中$z$s" },
    { L":POLICEMODE:",          L"$fff法$z$s" },
    { L":slayyy:",              L"$fff答$z$s" },
    { L":middle finger:",       L"$fff不$z$s" },
    { L":rofl:",                L"$fff正$z$s" },
    { L":cheese:",              L"$fff确$z$s" },
    { L":handshake:",           L"$fff未$z$s" },
    { L":cooking:",             L"$fff知$z$s" },
    { L":trolling:",            L"$fff代$z$s" },
    { L":infinitycar:",         L"$fff受$z$s" },
    { L":metronome:",           L"$fff址$z$s" },
    { L":noahglowup:",          L"$fff请$z$s" },
    { L":oiia:",                L"$fff分$z$s" },
    { L":puzzle:",              L"$fff再$z$s" },
    { L":baguette:",            L"$fff匙$z$s" },

	                    // Christmas

    { L":candles:",             L"$fff支$z$s" },
    { L":cadycane:",            L"$fff持$z$s" },
    { L":carols:",              L"$fff版$z$s" },
    { L":decorations:",         L"$fff后$z$s" },
    { L":family:",              L"$fff用$z$s" },
    { L":gift:",                L"$fff排$z$s" },
    { L":gingerbread:",         L"$fff名$z$s" },
    { L":lucky:",               L"$fff获$z$s" },
    { L":magic:",               L"$fff得$z$s" },
    { L":mass:",                L"$fff信$z$s" },
    { L":preparations:",        L"$fff息$z$s" },
    { L":sleigh:",              L"$fff语$z$s" },
    { L":snowman:",             L"$fff言$z$s" },
    { L":star:",                L"$fff登$z$s" },
    { L":table:",               L"$fff口$z$s" },
    { L":tree:",                L"$fff已$z$s" },
    { L":turkey:",              L"$fff经$z$s" },
    { L":wreath:",              L"$fff从$z$s" },
    { L":yulelog:",             L"$fff另$z$s" },

                        // Kacky

    { L":niatibot:",            L"$fff尝$z$s" },
    { L":concernfroge:",        L"$fff组$z$s" },
    { L":conceited:",           L"$fff玩$z$s" },
    { L":010:",                 L"$fff伙$z$s" },
    { L":cheesed:",             L"$fff伴$z$s" },
    { L":report:",              L"$fff件$z$s" },
    { L":glorpa:",              L"$fff存$z$s" },
    { L":milki:",               L"$fff保$z$s" },
    { L":modCheckS:",           L"$fff求$z$s" },
    { L":x0r6ztGiggle:",        L"$fff放$z$s" },
    { L":LIS:",                 L"$fff弃$z$s" },
};

const int kEmojiCount = sizeof(kEmojis) / sizeof(kEmojis[0]);